source(here::here("TreeSetAnalysisScripts", "code", "analysis", "path_utils.R"))

# ------------------------------------------------------------------------------#
#                         Demo Regression Runner                                 #
# ------------------------------------------------------------------------------#
# Purpose:
#   Run the TreeSet socio-ecology regression model on the small demo datasets
#   generated by 01_prepare_demo_datasets.R.
#
# Inputs:
# - demo/datasets_and_trees_demo/ [Directory: demo CSV/tree pairs]
#
# Outputs:
# - demo/regression_results_demo/ [Directory: per-dataset regression results]
# - demo/regression_slopes_demo/ [Directory: per-dataset slope summaries]
# - demo/demo_summary/demo_regression_run_summary.csv [CSV: run summary]
# ------------------------------------------------------------------------------#

pacman::p_load(
  "ade4", "ape", "data.table", "dismo", "here", "INLA", "nlme",
  "picante", "progress", "sp", "spdep", "tidyverse"
)

demo_here <- function(...) {
  here::here("TreeSetAnalysisScripts", "demo", ...)
}

demo_dir_create <- function(...) {
  dir_path <- demo_here(...)
  if (!dir.exists(dir_path)) {
    dir.create(dir_path, recursive = TRUE, showWarnings = FALSE)
  }
  dir_path
}

set.seed(20260407)

demo_data_dir <- demo_here("datasets_and_trees_demo")
demo_results_dir <- demo_dir_create("regression_results_demo")
demo_slopes_dir <- demo_dir_create("regression_slopes_demo")
demo_summary_dir <- demo_dir_create("demo_summary")
demo_graph_dir <- demo_dir_create("cl_graph_demo")

if (!dir.exists(demo_data_dir)) {
  stop("Demo dataset directory is missing: ", demo_data_dir)
}

st0 <- list.files(demo_data_dir, pattern = "_2\\.csv$", full.names = TRUE)
st2a <- list.files(demo_data_dir, pattern = "_2\\.csv$", full.names = FALSE)

if (length(st0) == 0) {
  stop("No demo dataset CSV files were found in ", demo_data_dir)
}

st2b <- gsub(".csv", "", st2a, fixed = TRUE)
st2b <- gsub("alltime", "all_time", st2b, fixed = TRUE)
st3a <- read.table(text = st2b, sep = "_", stringsAsFactors = FALSE)

files1 <- data.frame(st3a, filen = st0, uni = st2b, stringsAsFactors = FALSE)
files1[, "V7"] <- as.numeric(gsub("XXX", "", files1[, "V7"]))
files1$V3[files1$V3 == "extant"] <- -1
files1 <- files1[order(files1$V2, files1$V7), ]

tt0 <- list.files(demo_data_dir, pattern = "_2\\.tre$", full.names = TRUE)
tt2a <- list.files(demo_data_dir, pattern = "_2\\.tre$", full.names = FALSE)
tt2a <- gsub(".tre", "", tt2a, fixed = TRUE)
tt2a <- gsub("alltime", "all_time", tt2a, fixed = TRUE)
tt3a <- read.table(text = tt2a, sep = "_", stringsAsFactors = FALSE)
tt3a$V6 <- gsub("time", "", tt3a$V6, fixed = TRUE)
tt3a$V6 <- as.numeric(tt3a$V6)
tt <- data.frame(tt3a, filen = tt0, uni = tt2a, stringsAsFactors = FALSE)
tt[, "V7"] <- as.numeric(gsub("XXX", "", tt[, "V7"]))
tt$V3[tt$V3 == "extant"] <- -1

e <- simpleError("test error")

cutD <- function(x, n) {
  cut(
    x,
    breaks = c(stats::quantile(x, probs = seq(0, 1, by = 1 / n), na.rm = TRUE)),
    include.lowest = TRUE
  )
}

pb <- progress::progress_bar$new(
  format = "  Processing [:bar] :percent in :elapsed, ETA: :eta",
  total = nrow(files1),
  clear = FALSE,
  width = 60
)

INLA::inla.setOption("num.threads", "4:1")

run_summary <- vector("list", nrow(files1))
typeX <- "poisson"

for (ii in seq_len(nrow(files1))) {
  pb$tick()
  start_time <- Sys.time()

  files2 <- files1[ii, ]
  tree1 <- tt[tt$uni == files2$uni, ]

  result_file <- file.path(
    demo_results_dir,
    paste0("results_", files1[ii, "uni"], "_", typeX, "_regressions25.csv")
  )
  slope_file <- file.path(
    demo_slopes_dir,
    paste0("results_", files1[ii, "uni"], "_slopes25.csv")
  )

  summary_row <- data.frame(
    input_id = files1[ii, "uni"],
    tree_id = files1[ii, "V3"],
    time_slice = files1[ii, "V7"],
    model_family = typeX,
    status = "started",
    result_file = basename(result_file),
    slopes_file = basename(slope_file),
    error_message = NA_character_,
    elapsed_seconds = NA_real_,
    stringsAsFactors = FALSE
  )

  if (file.exists(result_file)) {
    summary_row$status <- "skipped_existing"
    summary_row$elapsed_seconds <- as.numeric(difftime(Sys.time(), start_time, units = "secs"))
    run_summary[[ii]] <- summary_row
    next
  }

  res4 <- NULL
  quads2 <- NULL

  es4 <- data.table::fread(as.character(files2$filen), stringsAsFactors = FALSE)
  row.names(es4) <- as.character(es4$tips)
  tr1 <- ape::read.tree(file = as.character(tree1$filen))

  node_ages <- picante::node.age(tr1)$ages
  tot_time <- max(node_ages)

  es4$pred <- NA_real_
  kf <- 1
  loos_type <- "none"

  estr <- data.table::copy(es4)
  estr$y <- estr$length
  estr$y2 <- estr$y
  estr$names <- seq_len(nrow(estr))

  esqp <- estr
  sp::coordinates(esqp) <- ~ longitude + latitude
  rownames(esqp@data) <- esqp@data$names

  nbs <- spdep::knearneigh(sp::coordinates(esqp), k = 10, longlat = TRUE)
  nbs <- spdep::knn2nb(nbs, sym = TRUE)
  spdep::nb2mat(nbs, style = "B", zero.policy = TRUE)

  graph_path <- file.path(demo_graph_dir, paste0("cl_graph_", ii))
  spdep::nb2INLA(graph_path, nbs)
  H <- INLA::inla.read.graph(filename = graph_path)

  phylo_covar_mat <- ape::vcv(tr1)
  phylo_covar_mat <- phylo_covar_mat / max(phylo_covar_mat)
  phylo_covar_mat <- phylo_covar_mat /
    exp(determinant(phylo_covar_mat)$modulus[1] / nrow(phylo_covar_mat))
  phylo_prec_mat <- solve(phylo_covar_mat)

  pcprior <- list(prec = list(prior = "pc.prec", param = c(0.36, 0.1)))

  estr2 <- cbind(
    estr,
    data.frame(
      species = rownames(phylo_prec_mat),
      phy_id = seq_len(nrow(phylo_prec_mat)),
      stringsAsFactors = FALSE
    )
  )

  estr2$clade_age_g <- INLA::inla.group(estr2$clade_age, n = 15)
  estr2$island2 <- estr2$island
  estr2$island2[estr2$island > 0.5] <- "islands"
  estr2$island2[estr2$island < 0.5] <- "mainland"
  estr2$subregion <- estr$names

  model1 <- "include_REGION"
  formx <- stats::formula(
    paste0(
      "y~ island + area_log + distancetocityyear2 + popd_log + friction_log + ",
      "f(clade_age_g, model='rw2', constr = TRUE, scale.model = TRUE) + ",
      "f(subregion, model = 'bym2', graph = H, constr = TRUE, scale.model = TRUE) + ",
      "f(phy_id, model = 'generic0', Cmatrix = phylo_prec_mat, constr = TRUE, hyper = pcprior)"
    )
  )

  lm.brown <- tryCatch(
    INLA::inla(
      formx,
      data = estr2,
      control.fixed = list(
        mean = 0,
        prec = 1 / (0.3^2),
        mean.intercept = 0,
        prec.intercept = 1 / (0.6^2)
      ),
      family = typeX,
      control.family = list(list(link = "default")),
      control.compute = list(config = TRUE, dic = FALSE, waic = TRUE, cpo = TRUE),
      control.predictor = list(compute = TRUE, link = 1)
    ),
    error = function(err) err
  )

  if (inherits(lm.brown, "simpleError")) {
    summary_row$status <- "model_error"
    summary_row$error_message <- conditionMessage(lm.brown)
    summary_row$elapsed_seconds <- as.numeric(difftime(Sys.time(), start_time, units = "secs"))
    run_summary[[ii]] <- summary_row
    next
  }

  pred1 <- lm.brown$summary.linear.predictor[seq_len(nrow(estr)), ]
  es4$pred[kf == 1] <- pred1[kf == 1, 1]
  es4$resid <- estr$y2 - exp(pred1$mean)

  psudor2 <- stats::cor(exp(es4$pred), estr$y, method = "pearson", use = "complete.obs")
  rmse1 <- sqrt(mean((estr$y - es4$pred)^2, na.rm = TRUE))
  man1 <- data.frame(obs = NA, pvalue = NA)

  res1 <- lm.brown$summary.fixed
  res1$name <- row.names(res1)
  res1$sig1 <- 0
  res1$sig1[
    (res1$`0.025quant` < 0 & res1$`0.975quant` < 0) |
      (res1$`0.025quant` > 0 & res1$`0.975quant` > 0)
  ] <- 1
  res1$mean_sig <- res1$mean * res1$sig1

  colsX <- c("island", "area_log", "distancetocityyear2", "popd_log", "friction_log")
  cols_log <- c("area_log", "popd_log", "friction_log")

  for (col1 in colsX) {
    if (!col1 %in% res1$name) {
      next
    }

    col_raw <- paste0(gsub("_log", "", col1, fixed = TRUE), "_raw")
    if (!col_raw %in% names(estr2)) {
      next
    }

    raw_vec <- estr2[[col_raw]]
    if (all(is.na(raw_vec))) {
      next
    }

    trans_vec <- if (col1 %in% cols_log) log1p(raw_vec) else raw_vec
    mu <- mean(trans_vec, na.rm = TRUE)
    sd_val <- stats::sd(trans_vec, na.rm = TRUE)
    if (is.na(sd_val) || sd_val == 0) {
      sd_val <- 1
    }

    x_values <- seq(min(raw_vec, na.rm = TRUE), max(raw_vec, na.rm = TRUE), length.out = 200)
    trans_x <- if (col1 %in% cols_log) {
      (log1p(x_values) - mu) / sd_val
    } else {
      (x_values - mu) / sd_val
    }

    quads1 <- data.frame(
      col = col1,
      x = x_values,
      y = res1$mean[res1$name == col1] * trans_x + res1$mean[res1$name == "(Intercept)"],
      y2 = res1$mean_sig[res1$name == col1] * trans_x +
        res1$mean_sig[res1$name == "(Intercept)"],
      yearbp = files1[ii, "V7"],
      tree = files1[ii, "V3"],
      kfold = 1,
      stringsAsFactors = FALSE
    )

    if (is.null(quads2)) {
      quads2 <- quads1
    } else {
      quads2 <- rbind(quads2, quads1)
    }
  }

  if (!is.null(quads2)) {
    utils::write.csv(quads2, file = slope_file, row.names = FALSE)
  }

  res1$n <- NA
  res1$model <- model1
  res1$model2 <- nrow(estr2)
  res1$kfold <- 1
  res1$lastkfold <- 1
  res1$AIC <- lm.brown$waic$waic
  res1$Time <- tot_time - (files1[ii, "V7"] / 1000)
  res1$Crown <- tot_time
  res1$Time2 <- files1[ii, "V7"] * -1
  res1$loop <- ii
  res1$Form <- as.character(stats::formula(formx))[3]
  res1$type <- typeX
  res1$loos_type <- loos_type
  res1$model_name <- NA
  res1$shapiro <- NA
  res1$mantcor <- man1$obs
  res1$mantel <- man1$pvalue
  res1$psudor2 <- psudor2
  res1$rmse <- rmse1
  res1$tree_type <- files1[ii, "V2"]
  res1$tree <- files1[ii, "V3"]
  res1$group <- files1[ii, "V4"]

  res4 <- res1
  utils::write.csv(res4, file = result_file, row.names = FALSE)

  summary_row$status <- "success"
  summary_row$elapsed_seconds <- as.numeric(difftime(Sys.time(), start_time, units = "secs"))
  run_summary[[ii]] <- summary_row
}

summary_table <- do.call(rbind, run_summary)
utils::write.csv(
  summary_table,
  file = file.path(demo_summary_dir, "demo_regression_run_summary.csv"),
  row.names = FALSE
)
